//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emergencias_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_Prueba
    {
        public int ID_Datos_Inspeccion { get; set; }
        public string URI { get; set; }
        public Nullable<int> EmergenciaID { get; set; }
        public Nullable<System.DateTime> Fecha_Visita { get; set; }
        public Nullable<bool> Solo_Externa { get; set; }
        public Nullable<bool> Valoracion_Realizada { get; set; }
        public Nullable<int> ID_Tipo_Acceso { get; set; }
        public Nullable<int> ID_Fallas_Suministro_Electrico { get; set; }
        public Nullable<bool> Focos_Contaminacion { get; set; }
        public Nullable<bool> Informe_Condiciones_Riesgo { get; set; }
        public Nullable<int> ID_Institucion_Informe { get; set; }
        public string Otro_Institucion_Informe { get; set; }
    }
}
