//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emergencias_api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class m_Emergencias_V3Entities : DbContext
    {
        public m_Emergencias_V3Entities()
            : base("name=m_Emergencias_V3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Datos_Prueba> Datos_Prueba { get; set; }
        public virtual DbSet<Emergencia> Emergencias { get; set; }
        public virtual DbSet<Institucione> Instituciones { get; set; }
        public virtual DbSet<Tipo_Acceso> Tipo_Acceso { get; set; }
        public virtual DbSet<Tipo_SI_No_NS> Tipo_SI_No_NS { get; set; }
    }
}
