//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emergencias_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_SI_No_NS
    {
        public byte ID { get; set; }
        public string Descripcion { get; set; }
    }
}
